=== owncloud/ocis/tests/ccs/tests/CalDAV/caldavtest.dtd
<!--
 Copyright (c) 2006-2016 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT caldavtest (description?, require-feature?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT require-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>
	<!ELEMENT exclude-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT pause EMPTY>

	<!ELEMENT request (require-feature?, exclude-feature?, method, ruri*, header*, data?, verify*,
						graburi?, grabcount?, grabheader*, grabproperty*, grabelement*, grabjson*, grabcalproperty*, grabcalparameter*)>
		<!ATTLIST request host2 (yes|no) "no"
						 auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 cert CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no"
						 iterate-data (yes|no) "no"
						 wait-for-success (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
			<!ATTLIST ruri quote (yes|no) "yes">
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT data (content-type, (filepath | generator), substitute*)>
			<!ATTLIST data substitutions (yes|no) "yes"
						   generate      (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>
			<!ELEMENT generator (callback, arg*)>
			<!ELEMENT substitute (name, value)>

		<!ELEMENT verify (require-feature?, exclude-feature?, callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value*)>
		
		<!ELEMENT graburi (#PCDATA)>

		<!ELEMENT grabcount (#PCDATA)>

		<!ELEMENT grabheader (name, variable)>
	
		<!ELEMENT grabproperty (property, variable)>
			<!ELEMENT property (#PCDATA)>
			<!ELEMENT variable (#PCDATA)>

		<!ELEMENT grabelement (name, parent*, variable+)>

		<!ELEMENT grabjson (pointer, variable+)>

		<!ELEMENT grabcalproperty (name, variable)>
		<!ELEMENT grabcalparameter (name, variable)>

	<!ELEMENT test-suite (require-feature?, exclude-feature?, test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no"
							only (yes|no) "no"
							change-uid (yes|no) "no">
	
		<!ELEMENT test (require-feature?, exclude-feature?, description?, (request|pause)+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no"
						  only (yes|no) "no">

=== owncloud/ocis/tests/caldav/caldavtest/tests/CalDAV/well-known.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2016 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test the well-known collection</description>

	<require-feature>
		<feature>caldav</feature>
		<feature>well-known</feature>
	</require-feature>

	<start/>

	<test-suite name='Simple GET tests'>
		<test name='1'>
			<description>Simple GET on top-level authenticated</description>
			<request>
				<method>GET</method>
				<ruri>/.well-known/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Simple GET on top-level unauthenticated</description>
			<request auth='no'>
				<method>GET</method>
				<ruri>/.well-known/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Simple GET on caldav authenticated</description>
			<request>
				<method>GET</method>
				<ruri>/.well-known/caldav</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>301</value>
					</arg>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$hostssl:/</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>Simple GET on caldav unauthenticated</description>
			<request auth='no'>
				<method>GET</method>
				<ruri>/.well-known/caldav</ruri>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>301</value>
					</arg>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$hostssl:/</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='Simple PROPFIND tests'>
		<test name='1'>
			<description>Simple PROPFIND on top-level authenticated</description>
			<request>
				<method>PROPFIND</method>
				<ruri>/.well-known/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>Simple PROPFIND on top-level unauthenticated</description>
			<request auth='no'>
				<method>PROPFIND</method>
				<ruri>/.well-known/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Simple PROPFIND on caldav authenticated</description>
			<request>
				<method>PROPFIND</method>
				<ruri>/.well-known/caldav</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>301</value>
					</arg>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$hostssl:/</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>Simple PROPFIND on caldav unauthenticated</description>
			<request auth='no'>
				<method>PROPFIND</method>
				<ruri>/.well-known/caldav</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>301</value>
					</arg>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$hostssl:/</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>PROPFIND Depth:infinity on top-level authenticated</description>
			<request>
				<method>PROPFIND</method>
				<ruri>/.well-known/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/resourcetype.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>PROPFIND Depth:infinity on caldav authenticated</description>
			<request>
				<method>PROPFIND</method>
				<ruri>/.well-known/caldav</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/Common/PROPFIND/resourcetype.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>301</value>
					</arg>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Location$$hostssl:/</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>

</caldavtest>

=== owncloud/ocis/tests/ccs/tests/CardDAV/mkcol.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2016 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<require-feature>
		<feature>carddav</feature>
	</require-feature>

	<start/>
	
	<test-suite name='OPTIONS header'>
		<test name='1' ignore='yes'>
			<description>OPTIONS DAV: header does not contain extended-mkcol</description>
			<request>
				<method>OPTIONS</method>
				<ruri>$addressbookhome1:/</ruri>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>*DAV!.*extended-mkcol.*</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>OPTIONS Allow: header does not contain MKCOL</description>
			<request>
				<method>OPTIONS</method>
				<ruri>$addressbookhome1:/</ruri>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>*Allow!.*MKCOL.*</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>OPTIONS Allow: header does not contain MKCALENDAR</description>
			<request>
				<method>OPTIONS</method>
				<ruri>$addressbookhome1:/</ruri>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>*Allow!.*MKCALENDAR.*</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='MKCOL with body'>
		<test name='1'>
			<description>MKCOL with correct request body</description>
			<request end-delete='yes'>
				<method>MKCOL</method>
				<ruri>$addressbookhome1:/adbktest1/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/mkcol/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>403</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>

</caldavtest>

=== owncloud/ocis/tests/ccs/tests/CardDAV/get.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2016 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
	<description>Test GET on collections to ensure proper directory listing</description>

	<require-feature>
		<feature>carddav</feature>
	</require-feature>

	<start/>
	<test-suite name='GET on resource'>
		<test name='1'>
			<description>GET from address book collection</description>
			<request end-delete="no">
				<method>PUT</method>
				<ruri>$addressbookpath1:/1.vcf</ruri>
				<data>
					<content-type>text/vcard; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vcardput/1.vcf</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>$addressbookpath1:/1.vcf</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>addressDataMatch</callback>
					<arg>
						<name>filepath</name>
						<value>Resource/CardDAV/vcardput/1.vcf</value>
					</arg>
				</verify>
			</request>
		</test>
		<!-- test name='2'>
			<description>GET on user/addressbook</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookpath1:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>1.vcf</value>
					</arg>
				</verify>
			</request>
			<request>
				<method>DELETE</method>
				<ruri>$addressbookpath1:/1.vcf</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>Get on regular collection</description>
			<request>
				<method>GET</method>
				<ruri>$principaluri1:</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>addressbook</value>
						<value>search</value>
					</arg>
				</verify>
			</request>
		</test -->
	</test-suite>

	<test-suite name='GET on collections'>
		<require-feature>
			<feature>directory listing</feature>
		</require-feature>
		<test name='1'>
			<description>GET on addressbook collection</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookpath1:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Etag</value>
						<value>Last-Modified</value>
					</arg>
				</verify>
				<grabheader>
					<name>Etag</name>
					<variable>$etag:</variable>
				</grabheader>
				<grabheader>
					<name>Last-Modified</name>
					<variable>$last-modified:</variable>
				</grabheader>
			</request>
		</test>
		<test name='2'>
			<require-feature>
				<feature>regular-collection</feature>
			</require-feature>
			<description>Get on regular collection</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookhome1:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Etag</value>
						<value>Last-Modified</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>GET on addressbook collection</description>
			<request>
				<method>DELAY</method>
				<ruri>1</ruri>
			</request>
			<request end-delete="yes">
				<method>PUT</method>
				<ruri>$addressbookpath1:/2.vcf</ruri>
				<data>
					<content-type>text/vcard; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vcardput/2.vcf</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
			<request>
				<method>GET</method>
				<ruri>$addressbookpath1:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>ETag!$etag:</value>
						<value>Last-Modified!$last-modified:</value>
					</arg>
				</verify>
				<grabheader>
					<name>Etag</name>
					<variable>$etag2:</variable>
				</grabheader>
				<grabheader>
					<name>Last-Modified</name>
					<variable>$last-modified2:</variable>
				</grabheader>
			</request>
		</test>
		<test name='5'>
			<description>Conditional GET on addressbook collection</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>If-None-Match</name>
					<value>$etag2:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>304</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>Conditional GET on addressbook collection</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>If-Modified-Since</name>
					<value>$last-modified2:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>304</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<test-suite name='GET on home'>
		<require-feature>
			<feature>directory listing</feature>
		</require-feature>
		<test name='1'>
			<description>GET on addressbook home</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookhome1:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Etag</value>
						<value>Last-Modified</value>
					</arg>
				</verify>
				<grabheader>
					<name>Etag</name>
					<variable>$etag1:</variable>
				</grabheader>
				<grabheader>
					<name>Last-Modified</name>
					<variable>$last-modified1:</variable>
				</grabheader>
			</request>
		</test>
		<test name='4'>
			<description>Conditional GET on addressbook home</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookhome1:/</ruri>
				<header>
					<name>If-None-Match</name>
					<value>$etag2:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>304</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>Conditional GET on addressbook home</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookhome1:/</ruri>
				<header>
					<name>If-Modified-Since</name>
					<value>$last-modified1:</value>
				</header>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>304</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>Delete the addressbook</description>
			<request>
				<method>DELAY</method>
				<ruri>1</ruri>
			</request>
			<request end-delete="yes">
				<method>DELETE</method>
				<ruri>$addressbookpath1:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='7'>
			<description>GET on addressbook home, changed headers</description>
			<request>
				<method>GET</method>
				<ruri>$addressbookhome1:/</ruri>
				<verify>
					<callback>statusCode</callback>
				</verify>
				<verify>
					<callback>header</callback>
					<arg>
						<name>header</name>
						<value>Etag!$etag1:</value>
						<value>Last-Modified!$last-modified1:</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>

	<end/>

</caldavtest>

=== owncloud/ocis/tests/ccs/tests/CardDAV/propfind.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2016 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>

	<require-feature>
		<feature>carddav</feature>
	</require-feature>

	<start/>
	
	<test-suite name='regular prop finds'>
		<test name='1'>
			<description>PROPFIND of basic properties depth=0</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of basic properties depth=1</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of basic properties depth=infinity</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/1.xml</filepath>
				</data>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>{DAV:}propfind-finite-depth</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPFIND getcontentlength=0</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/7.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}getcontentlength$</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>PROPFIND of non-existent addressbook depth=1</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookhome1:/foobar/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>404</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='6'>
			<description>PROPFIND of non-existent addressbook child depth=1</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookhome1:/foobar/foo.ics</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>404</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='7'>
			<description>PROPFIND of non-existent addressbook child collection depth=1</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookhome1:/foobar/example/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/1.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>404</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='prop names'>
		<test name='1'>
			<description>PROPFIND of property names depth=0</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/2.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of property names depth=1</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/2.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of property names depth=infinity</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/2.xml</filepath>
				</data>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>{DAV:}propfind-finite-depth</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='prop all'>
		<test name='1'>
			<description>PROPFIND of all properties depth=0</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/3.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of all properties depth=1</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>1</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/3.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND of all properties depth=infinity</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>infinity</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/3.xml</filepath>
				</data>
				<verify>
					<callback>prepostcondition</callback>
					<arg>
						<name>error</name>
						<value>{DAV:}propfind-finite-depth</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<test-suite name='prop errors'>
		<test name='1'>
			<description>PROPFIND with invalid elements</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/4.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>4xx</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPFIND of unknown element</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/5.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
					<arg>
						<name>status</name>
						<value>4xx</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPFIND with one unknown property</description>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vpropfinds/6.xml</filepath>
				</data>
				<verify>
					<callback>statusCode</callback>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>
