=== owncloud/ocis/tests/ccs/tests/CalDAV/caldavtest.dtd
<!--
 Copyright (c) 2006-2016 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT caldavtest (description?, require-feature?, start, test-suite*, end) >
	<!ATTLIST caldavtest ignore-all (yes|no) "no">

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT require-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>
	<!ELEMENT exclude-feature (feature*)>
		<!ELEMENT feature (#PCDATA)>

	<!ELEMENT start (request*)>
	<!ELEMENT end (request*)>

	<!ELEMENT pause EMPTY>

	<!ELEMENT request (require-feature?, exclude-feature?, method, ruri*, header*, data?, verify*,
						graburi?, grabcount?, grabheader*, grabproperty*, grabelement*, grabjson*, grabcalproperty*, grabcalparameter*)>
		<!ATTLIST request host2 (yes|no) "no"
						 auth (yes|no) "yes"
						 user CDATA ""
						 pswd CDATA ""
						 cert CDATA ""
						 end-delete (yes|no) "no"
						 print-response (yes|no) "no"
						 iterate-data (yes|no) "no"
						 wait-for-success (yes|no) "no">
		
		<!ELEMENT method (#PCDATA)>
		<!ELEMENT ruri (#PCDATA)>
			<!ATTLIST ruri quote (yes|no) "yes">
		<!ELEMENT header (name, value)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT data (content-type, (filepath | generator), substitute*)>
			<!ATTLIST data substitutions (yes|no) "yes"
						   generate      (yes|no) "no">
			<!ELEMENT content-type (#PCDATA)>
			<!ELEMENT filepath (#PCDATA)>
			<!ELEMENT generator (callback, arg*)>
			<!ELEMENT substitute (name, value)>

		<!ELEMENT verify (require-feature?, exclude-feature?, callback, arg*)>
			
				<!ELEMENT callback (#PCDATA)>
				<!ELEMENT arg (name, value*)>
		
		<!ELEMENT graburi (#PCDATA)>

		<!ELEMENT grabcount (#PCDATA)>

		<!ELEMENT grabheader (name, variable)>
	
		<!ELEMENT grabproperty (property, variable)>
			<!ELEMENT property (#PCDATA)>
			<!ELEMENT variable (#PCDATA)>

		<!ELEMENT grabelement (name, parent*, variable+)>

		<!ELEMENT grabjson (pointer, variable+)>

		<!ELEMENT grabcalproperty (name, variable)>
		<!ELEMENT grabcalparameter (name, variable)>

	<!ELEMENT test-suite (require-feature?, exclude-feature?, test*)>
		<!ATTLIST test-suite name CDATA #REQUIRED
							ignore (yes|no) "no"
							only (yes|no) "no"
							change-uid (yes|no) "no">
	
		<!ELEMENT test (require-feature?, exclude-feature?, description?, (request|pause)+)>
			<!ATTLIST test name CDATA #REQUIRED
						  count CDATA "1"
						  stats (yes|no) "no"
						  ignore (yes|no) "no"
						  only (yes|no) "no">

=== owncloud/ocis/tests/ccs/tests/CardDAV/proppatch.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2016 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>

	<require-feature>
		<feature>carddav</feature>
	</require-feature>

	<start/>
	
	<test-suite name='prop patches'>
		<test name='1'>
			<description>PROPPATCH of details: good</description>
			<request>
				<method>PROPPATCH</method>
				<ruri>$addressbookpath1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/1.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details</value>
						<value>{DAV:}details2</value>
					</arg>
				</verify>
			</request>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details$My Name</value>
						<value>{DAV:}details2$My Name 2</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPPATCH of details: remove it</description>
			<request>
				<method>PROPPATCH</method>
				<ruri>$addressbookpath1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/3.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details</value>
					</arg>
				</verify>
			</request>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details2$My Name 2</value>
					</arg>
					<arg>
						<name>badprops</name>
						<value>{DAV:}details</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='3'>
			<description>PROPPATCH remove non-existant</description>
			<request>
				<method>PROPPATCH</method>
				<ruri>$addressbookpath1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/4.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}missing</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='4'>
			<description>PROPPATCH of resourcetype: fails</description>
			<request>
				<method>PROPPATCH</method>
				<ruri>$addressbookpath1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/5.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>badprops</name>
						<value>{DAV:}details</value>
						<value>{DAV:}details2</value>
						<value>{DAV:}resourcetype</value>
					</arg>
				</verify>
			</request>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details2$My Name 2</value>
					</arg>
					<arg>
						<name>badprops</name>
						<value>{DAV:}details</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='5'>
			<description>PROPPATCH of encoded value</description>
			<request>
				<method>PROPPATCH</method>
				<ruri>$addressbookpath1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/8.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}displayname</value>
					</arg>
				</verify>
			</request>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/9.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}displayname$addressbook &lt;- &amp; ]]&gt;</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	<test-suite name='prop patch property attributes'>
		<test name='1'>
			<description>PROPPATCH with property XML attribute</description>
			<request>
				<method>PROPPATCH</method>
				<ruri>$addressbookpath1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/6.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details</value>
					</arg>
				</verify>
			</request>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/7.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details$My Name</value>
					</arg>
				</verify>
				<verify>
					<callback>dataString</callback>
					<arg>
						<name>contains</name>
						<value>details xml:lang='en'</value>
					</arg>
				</verify>
			</request>
		</test>
		<test name='2'>
			<description>PROPPATCH of details: remove it</description>
			<request>
				<method>PROPPATCH</method>
				<ruri>$addressbookpath1:/</ruri>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/3.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details</value>
					</arg>
				</verify>
			</request>
			<request>
				<method>PROPFIND</method>
				<ruri>$addressbookpath1:/</ruri>
				<header>
					<name>Depth</name>
					<value>0</value>
				</header>
				<data>
					<content-type>text/xml; charset=utf-8</content-type>
					<filepath>Resource/CardDAV/vproppatches/2.xml</filepath>
				</data>
				<verify>
					<callback>propfindItems</callback>
					<arg>
						<name>okprops</name>
						<value>{DAV:}details2$My Name 2</value>
					</arg>
					<arg>
						<name>badprops</name>
						<value>{DAV:}details</value>
					</arg>
				</verify>
			</request>
		</test>
	</test-suite>
	
	<end/>
	
</caldavtest>

=== owncloud/ocis/tests/ccs/tests/CardDAV/ab-client.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE caldavtest SYSTEM "caldavtest.dtd">

<!--
 Copyright (c) 2006-2016 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<caldavtest>
    <description>Emulate the common behaviors of the AB client</description>

    <require-feature>
        <feature>carddav</feature>
    </require-feature>

    <start/>

    <test-suite name='Account setup'>
        <test name='1'>
            <description>PROPFIND principal - no authentication</description>
            <request auth="no">
                <method>PROPFIND</method>
                <ruri>$principal1:</ruri>
                <header>
                    <name>Depth</name>
                    <value>0</value>
                </header>
                <data>
                    <content-type>text/xml; charset=utf-8</content-type>
                    <filepath>Resource/CardDAV/vab-client/1.xml</filepath>
                </data>
                <verify>
                    <callback>statusCode</callback>
                    <arg>
                        <name>status</name>
                        <value>401</value>
                    </arg>
                </verify>
            </request>
        </test>
        <test name='2'>
            <description>PROPFIND principal - with authentication</description>
            <request>
                <method>PROPFIND</method>
                <ruri>$principal1:</ruri>
                <header>
                    <name>Depth</name>
                    <value>0</value>
                </header>
                <data>
                    <content-type>text/xml; charset=utf-8</content-type>
                    <filepath>Resource/CardDAV/vab-client/1.xml</filepath>
                </data>
                <verify>
                    <callback>statusCode</callback>
                    <arg>
                        <name>status</name>
                        <value>207</value>
                    </arg>
                </verify>
            </request>
        </test>
    </test-suite>

    <test-suite name='Polling'>
        <test name='1'>
            <description>PROPFIND addressbook home</description>
            <request>
                <method>PROPFIND</method>
                <ruri>$addressbookhome1:/</ruri>
                <header>
                    <name>Depth</name>
                    <value>1</value>
                </header>
                <data>
                    <content-type>text/xml; charset=utf-8</content-type>
                    <filepath>Resource/CardDAV/vab-client/2.xml</filepath>
                </data>
                <verify>
                    <callback>statusCode</callback>
                    <arg>
                        <name>status</name>
                        <value>207</value>
                    </arg>
                </verify>
            </request>
        </test>
    </test-suite>

    <end/>

</caldavtest>
